version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: lti_user
      POSTGRES_PASSWORD: FYA2wxe8anx-hnr_gzy
      POSTGRES_DB: lti_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
